### ISSUE TITLE
Java 8 lambda generation?

### ISSUE THREAD

**Issue by jonnermut** [kohsuke/codemodel#1]
Hi @kohsuke, I'm just trying to work out whether this fork has support for generating java 8 lambdas? I can see the support for java 8 in the API.

**Comment by jonnermut** [comment]
I'm guessing no. But this one does: https://github.com/phax/jcodemodel

**Comment by kohsuke** [comment]
Nice, that fork appears well maintained.

I created repo to save my projects from the EOL of java.net. I'll move my changes over to his version.
